### PR TITLE
Fix compilation errors in `jaspr_riverpod`

### PR DESCRIPTION
**Pull request by simolus3**
## Description

In version `3.0.2` of `package:riverpod`, the type of `Vsync` was changed from `void Function(void Function() task)` to `void Function(Task task)`.

That change broke `jaspr_riverpod`, since `_jasprVsync` does not conform to the changed function type. This applies a fix and raises the dependency on `riverpod` (because the fixed version would not work with riverpod `<3.0.2`).

## Type of Change

🛠️ Bug fix

## Ready Checklist

- [X] I've read the [Contribution Guide](https://github.com/schultek/jaspr/blob/main/CONTRIBUTING.md).
- [X] In case this PR changes one of the core packages, I've modified the respective **CHANGELOG.md** file using
      the [semantic_changelog](https://github.com/rrousselGit/semantic_changelog) format.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [X] I added myself to the AUTHORS file (optional, if you want to).

### CODE REVIEW

File: packages/jaspr_riverpod/lib/src/core/provider_scope.dart [hunk 1]
```diff
@@ -321,7 +321,7 @@ class _UncontrolledProviderScopeElement extends InheritedElement {
     setDependencies(dependent, getDependencies(dependent) ?? ProviderDependencies(dependent, this));
   }
 
-  void _jasprVsync(void Function() task) {
+  void _jasprVsync(Task task) {
     assert(_task == null, 'Only one task can be scheduled at a time');
```
Comment (schultek) [inline packages/jaspr_riverpod/lib/src/core/provider_scope.dart]: flutter_riverpod changed this assert to:

```dart
assert(
      _task == null
          // Checks for race conditions where a task has been completed in a different scope.
          // If so, it then becomes possible for another task to be scheduled
          // before this scoped had the opportunity to run its task.
          // TODO find a way to test this.
          ||
          _task!.completed,
      'Only one task can be scheduled at a time',
    );
```

and we should do the same

File: packages/jaspr_riverpod/lib/src/core/provider_scope.dart
Comment (schultek) [inline packages/jaspr_riverpod/lib/src/core/provider_scope.dart:1]: Also we should change the callsite of task (Line 337) to reflect the changes of flutter_riverpod:

```dart
final task = _task;
_task = null;
task?.call();
```

**Comment by simolus3** [comment]
Thanks for completing this 👍
